# Generated by Django 3.2.3 on 2024-10-19 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='subsribed_to',
            new_name='subsсribed_to',
        ),
    ]
