# Generated by Django 3.2.3 on 2024-09-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_alter_recipeingredient_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_url',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Короткий url'),
        ),
    ]
