# Generated by Django 3.2.3 on 2024-10-22 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_rename_favourite_favorite'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'recipe')},
        ),
    ]
