# Generated by Django 3.2.3 on 2024-10-22 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_alter_favorite_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set(),
        ),
    ]
