# Generated by Django 3.2.3 on 2024-10-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_alter_shoppingcart_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='short_code',
        ),
        migrations.AddField(
            model_name='recipe',
            name='short',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='short_url'),
        ),
    ]
