version: '3'
volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: stepan2204/foodgram_backend
    env_file: .env
    volumes:
      - media:/app/media
      - static:/backend_static/
    depends_on:
      - db

  frontend:
    env_file: .env
    image: stepan2204/foodgram_frontend
    volumes:
      - ./frontend/:/app/result_build/

  gateway:
    image: stepan2204/foodgram_gateway
    env_file: .env
    volumes:
      - static:/staticfiles/
      - media:/app/media
    depends_on:
      - backend
      - frontend
    ports:
      - 8000:80

